AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ai-log-triage-agent

  Sample SAM Template for ai-log-triage-agent
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: dist/handler.handler
      Runtime: nodejs20.x
      Timeout: 30

      Environment:
        Variables:
          TARGET_LOG_GROUP: "/aws/lambda/ai-log-triage-agent-HelloWorldFunction-wJyAeWBPF1lm"
          WINDOW_MINUTES: "10"
          MAX_SAMPLES: "40"
          OPENAI_MODEL: "gpt-4o-mini"
          MIN_ERRORS_FOR_AI: "1"

      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:FilterLogEvents
                - logs:DescribeLogGroups
                - logs:DescribeLogStreams
              Resource: "*"

      Events:
        Every15Minutes:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/handler.ts
        Minify: true
        Target: "es2020"

Outputs:
  HelloWorldFunction:
    Description: "Heartbeat Lambda ARN"
    Value: !GetAtt HelloWorldFunction.Arn