AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ai-log-triage-agent

  Sample SAM Template for ai-log-triage-agent
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: dist/handler.handler
      Runtime: nodejs20.x
      Timeout: 10
      Events:
        Every15Minutes:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/handler.ts
        Minify: true
        Target: "es2020"

Outputs:
  HelloWorldFunction:
    Description: "Heartbeat Lambda ARN"
    Value: !GetAtt HelloWorldFunction.Arn
